//Uncomment as you use them then comment out the ones you do not need

//get all recipes
GET http://localhost:3000/recipes 


//get a single recipe
//GET http://localhost:3000/recipes/ <=id 



//create a recipe
//POST http://localhost:3000/recipes
//Content-Type: application/json

//{
//    referer to JSON foler for example input
//}


//update a recipe
//PUT http://localhost:3000/recipes/ <=id
//Content-Type: application/json

//{
//    referer to JSON foler for example input
//}

//delete a recipe
//DELETE http://localhost:3000/recipes/ <=id