GET http://localhost:3000/users



//POST http://localhost:4040/users
//Content-Type: application/json
//
//{
//  "userFirstName": "Vishal",
//  "userLastName": "Vaid",
//  "email": "VV@gmail.com",
//  "password": "Admin2468@"
//}


//PUT http://localhost:4040/users/65ef53be2515a420828a406b
//Content-Type: application/json
//
//{
//  "userFirstName": "dayan",
//  "userLastName": "Frazap",
//  "email": "DayanFrazaojr@hotmail.com",
//  "password": "NeymarJr10"
//}