//Uncomment as you use them then comment out the ones you do not need
GET http://localhost:3000/users


//Create a user
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "userFirstName": "HAYLI",
  "userLastName": "BURNS",
  "email": "eb@gmail.com",
  "password": "Admin2468"
}



//update an user
###
PUT http://localhost:3000/users/65f35d33b13e2b66f8d8149a
Content-Type: application/json

{
  "userFirstName": "SABRINA",
  "userLastName": "SANDERS",
  "email": "SABRINA@hotmail.com",
  "password": "HELLO12345"
}


//delete an user
###

DELETE http://localhost:3000/users/65f1fbef1396674b9e788561
